# Generated by Django 4.0.2 on 2022-02-28 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Puesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puesto', models.CharField(max_length=25)),
                ('area', models.CharField(choices=[('Cal', 'Calidad'), ('Pro', 'Produccion'), ('Adm', 'Administracion'), ('Exp', 'Expedicion'), ('Tec', 'Tecnica'), ('Pos', 'Postulante')], max_length=3)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=15)),
                ('apellido', models.CharField(max_length=15)),
                ('dni', models.IntegerField(blank=True, default=0, max_length=8, null=True)),
                ('fec_nac', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('genero', models.CharField(choices=[('M', 'Hombre'), ('F', 'Mujer')], max_length=1)),
                ('activo', models.BooleanField(default=False, verbose_name='Empleador Activo?')),
                ('puesto', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='funciones.puesto')),
            ],
        ),
    ]
