# Generated by Django 4.0.2 on 2022-03-02 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=15)),
                ('apellido', models.CharField(max_length=15)),
                ('dni', models.IntegerField(blank=True, default=0, null=True)),
                ('fec_nac', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('genero', models.CharField(choices=[('M', 'Hombre'), ('F', 'Mujer')], max_length=1)),
                ('materia', models.ManyToManyField(blank=True, null=True, to='vista_Clases.Materia')),
            ],
        ),
    ]
