# Generated by Django 4.0.2 on 2022-05-17 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vista_Clases', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='materia',
            field=models.ManyToManyField(to='vista_Clases.Materia'),
        ),
    ]
